//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Living_Dex.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool includeGenderVariance {
            get {
                return ((bool)(this["includeGenderVariance"]));
            }
            set {
                this["includeGenderVariance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool includeGMax {
            get {
                return ((bool)(this["includeGMax"]));
            }
            set {
                this["includeGMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool includePikachuCap {
            get {
                return ((bool)(this["includePikachuCap"]));
            }
            set {
                this["includePikachuCap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool includeAlola {
            get {
                return ((bool)(this["includeAlola"]));
            }
            set {
                this["includeAlola"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool includeGalar {
            get {
                return ((bool)(this["includeGalar"]));
            }
            set {
                this["includeGalar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool includeHisui {
            get {
                return ((bool)(this["includeHisui"]));
            }
            set {
                this["includeHisui"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool includePaldea {
            get {
                return ((bool)(this["includePaldea"]));
            }
            set {
                this["includePaldea"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool includeUnown {
            get {
                return ((bool)(this["includeUnown"]));
            }
            set {
                this["includeUnown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool includeDeoxys {
            get {
                return ((bool)(this["includeDeoxys"]));
            }
            set {
                this["includeDeoxys"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool includeRotom {
            get {
                return ((bool)(this["includeRotom"]));
            }
            set {
                this["includeRotom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool includeDeerlingAndSawsbuck {
            get {
                return ((bool)(this["includeDeerlingAndSawsbuck"]));
            }
            set {
                this["includeDeerlingAndSawsbuck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool includeTherian {
            get {
                return ((bool)(this["includeTherian"]));
            }
            set {
                this["includeTherian"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool includeVivillon {
            get {
                return ((bool)(this["includeVivillon"]));
            }
            set {
                this["includeVivillon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool includeFlabebeFloetteAndFlorges {
            get {
                return ((bool)(this["includeFlabebeFloetteAndFlorges"]));
            }
            set {
                this["includeFlabebeFloetteAndFlorges"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool includeFurfrou {
            get {
                return ((bool)(this["includeFurfrou"]));
            }
            set {
                this["includeFurfrou"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool includePumpkabooAndGourgeist {
            get {
                return ((bool)(this["includePumpkabooAndGourgeist"]));
            }
            set {
                this["includePumpkabooAndGourgeist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool includeZygarde {
            get {
                return ((bool)(this["includeZygarde"]));
            }
            set {
                this["includeZygarde"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool includeOricorio {
            get {
                return ((bool)(this["includeOricorio"]));
            }
            set {
                this["includeOricorio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool includeLycanroc {
            get {
                return ((bool)(this["includeLycanroc"]));
            }
            set {
                this["includeLycanroc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool includeMinior {
            get {
                return ((bool)(this["includeMinior"]));
            }
            set {
                this["includeMinior"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool incluedToxtricityForms {
            get {
                return ((bool)(this["incluedToxtricityForms"]));
            }
            set {
                this["incluedToxtricityForms"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool includeSinisteaAndPolteageist {
            get {
                return ((bool)(this["includeSinisteaAndPolteageist"]));
            }
            set {
                this["includeSinisteaAndPolteageist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool includeAlcremie {
            get {
                return ((bool)(this["includeAlcremie"]));
            }
            set {
                this["includeAlcremie"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool includeUrshifu {
            get {
                return ((bool)(this["includeUrshifu"]));
            }
            set {
                this["includeUrshifu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool includeZarude {
            get {
                return ((bool)(this["includeZarude"]));
            }
            set {
                this["includeZarude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool includeUrsaluna {
            get {
                return ((bool)(this["includeUrsaluna"]));
            }
            set {
                this["includeUrsaluna"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool includeMaushold {
            get {
                return ((bool)(this["includeMaushold"]));
            }
            set {
                this["includeMaushold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool includeSquawkabilly {
            get {
                return ((bool)(this["includeSquawkabilly"]));
            }
            set {
                this["includeSquawkabilly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool includeTatsugiri {
            get {
                return ((bool)(this["includeTatsugiri"]));
            }
            set {
                this["includeTatsugiri"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool includeDudunsparce {
            get {
                return ((bool)(this["includeDudunsparce"]));
            }
            set {
                this["includeDudunsparce"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool includeGimmighoul {
            get {
                return ((bool)(this["includeGimmighoul"]));
            }
            set {
                this["includeGimmighoul"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool includePoltchageistAndSinistcha {
            get {
                return ((bool)(this["includePoltchageistAndSinistcha"]));
            }
            set {
                this["includePoltchageistAndSinistcha"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool includeBurmyAndWormadam {
            get {
                return ((bool)(this["includeBurmyAndWormadam"]));
            }
            set {
                this["includeBurmyAndWormadam"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool includeShaymin {
            get {
                return ((bool)(this["includeShaymin"]));
            }
            set {
                this["includeShaymin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool includeShellosAndGastrodon {
            get {
                return ((bool)(this["includeShellosAndGastrodon"]));
            }
            set {
                this["includeShellosAndGastrodon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool includeBasculin {
            get {
                return ((bool)(this["includeBasculin"]));
            }
            set {
                this["includeBasculin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool includeKeldeo {
            get {
                return ((bool)(this["includeKeldeo"]));
            }
            set {
                this["includeKeldeo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool includeHoopa {
            get {
                return ((bool)(this["includeHoopa"]));
            }
            set {
                this["includeHoopa"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool includeMagearna {
            get {
                return ((bool)(this["includeMagearna"]));
            }
            set {
                this["includeMagearna"] = value;
            }
        }
    }
}
